### ISSUE TITLE
formatting 

### ISSUE THREAD

**Issue by doctor-swag** [xxxOMA/exodus-lol#1]
hi, i saw the way you format your code and how you wrote it in your readme

Do you use an intellij auto reformatter for this as I am too lazy to do it myself :p 
Could you let me know please thanks

**Comment by YeahOMA** [comment]
No? I just like this way of styling my brackets

**Comment by doctor-swag** [comment]
Oh? I thought there might be some kind of auto-formatter out there, because when I code, my code often gets messy and I get IntelliJ auto reformat to clean it all up
would be nice if something like that formatter the way you wrote your code exists...

**Comment by doctor-swag** [comment]
accidentally closed, oops

**Comment by YeahOMA** [comment]
I have OCD so whenever I instantiate a class or make a variable I position it so that it doesnt trigger my tics lol
